### ISSUE TITLE
إقتراح : انظر مجموعة الرقمنة العربية

### ISSUE THREAD

**Issue by mwalid207** [mohammadmansour200/Tesseract-Arabic-Model#2]
السلام عليكم , أخي محمد , 
أظنك ستكون انت اضافة قوية لمجموعة الرقمنة العربية على التليجرام الذي انشئها الأستاذ / محمد الهمداني , وهاك رابطه  :
https://t.me/ArabicDigitalBooks

**Comment by mohammadmansour200** [comment]
وعليكم السلام ورحمة الله وبركاته.
جزاك الله خيرا
